# Generated by Django 4.2.3 on 2025-08-30 18:00

from django.db import migrations

def populate_templates(apps, schema_editor):
    """
    Populates the CertificateTemplate table with 14 predefined templates
    based on the finalized list.
    """
    CertificateTemplate = apps.get_model('certificates', 'CertificateTemplate')
    
    # Defines the complete set of all possible dynamic fields.
    # This ensures consistency across all templates.
    default_fields = {
        "cpi_or_cgpa": False,
        "backlog_status": False,
        "internship_company": False,
        "internship_duration": False,
        "application_id": False,
        "fee_amount": False,
        "fee_year": False,
        "caste_category": False,
        "gap_duration": False,
        "gap_reason": False,
        "transfer_reason": False,
        "medium_of_instruction": False,
        "rank_achieved": False,
        "total_students": False,
    }

    templates_data = [
        {
            "name": "Bonafide Certificate",
            "description": "Certifies that a student is currently enrolled in a specific program and academic session.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Bonafide Certificate</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that <b>{{ student.full_name }}</b> {{ student.parent_relation }} <b>{{ student.father_name }}</b> 
                    (Roll No. <b>{{ student.enrollment_no }}</b>) is a bonafide student of Four Year {{ student.degree }} 
                    in <b>{{ student.branch }}</b> for the academic session {{ student.academic_session }} at the University 
                    Institute of Engineering & Technology (UIET), Chhatrapati Shahu Ji Maharaj University, Kanpur.
                </p>
            """,
            "required_fields": default_fields
        },
        {
            "name": "Character Certificate",
            "description": "Certifies that a student who has completed their course bears a good moral character.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Character Certificate</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that <b>{{ student.full_name }}</b> {{ student.parent_relation }} <b>{{ student.father_name }}</b> 
                    (Roll No.: <b>{{ student.enrollment_no }}</b>) was a bonafide student of the four-year 
                    <b>{{ student.degree }}</b> in <b>{{ student.branch }}</b> 
                    (session {{ student.academic_session }}) at the University Institute of Engineering & Technology (UIET), 
                    Chhatrapati Shahu Ji Maharaj University, Kanpur.
                    <br><br>
                    To the best of my knowledge, {{ student.pronoun_he_she }} bears a good moral character.
                </p>
            """,
            "required_fields": default_fields
        },
        {
            "name": "Degree Completion Certificate",
            "description": "Certifies the successful completion of a degree program and the student's backlog status.",
            "body_template": """
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that <b>{{ student.full_name }}</b> {{ student.parent_relation }} <b>{{ student.father_name }}</b> 
                    (Roll No.: <b>{{ student.enrollment_no }}</b>) has successfully completed all the requirements for the award of the degree of 
                    <b>{{ student.degree }}</b> in <b>{{ student.branch }}</b> during the academic session {{ student.academic_session }}. 
                    As per our records, the student has <b>{{ request.request_data.backlog_status }}</b>.
                </p>
            """,
            "required_fields": {**default_fields, "backlog_status": True}
        },
        {
            "name": "Migration Certificate",
            "description": "States that the university has no objection to the student migrating to another institution.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Migration Certificate</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that the University has no objection to <b>{{ student.full_name }}</b> 
                    {{ student.parent_relation }} <b>{{ student.father_name }}</b>, a student of <b>{{ student.degree }}</b> 
                    in <b>{{ student.branch }}</b> with enrollment number <b>{{ student.enrollment_no }}</b>, migrating to another recognized university.
                </p>
            """,
            "required_fields": default_fields
        },
        {
            "name": "Internship Certificate",
            "description": "A general-purpose certificate for applying to internships.",
            "body_template": """
                 <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">TO WHOM IT MAY CONCERN</h2>
                 <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that <b>{{ student.full_name }}</b> (Roll No.: <b>{{ student.enrollment_no }}</b>) is a bonafide student of <b>{{ student.degree }}</b> 
                    in <b>{{ student.branch }}</b>. This certificate is issued for the purpose of applying for an internship at 
                    <b>{{ request.request_data.internship_company }}</b> for the duration of <b>{{ request.request_data.internship_duration }}</b>.
                </p>
            """,
             "required_fields": {**default_fields, "internship_company": True, "internship_duration": True}
        },
        {
            "name": "No Objection Certificate (Internship)",
            "description": "Provides no objection for a student to undertake a specific internship.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">NO OBJECTION CERTIFICATE</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that this institute has no objection to <b>{{ student.full_name }}</b> 
                    (Roll No.: <b>{{ student.enrollment_no }}</b>), a student of <b>{{ student.branch }}</b>, 
                    undertaking an internship at <b>{{ request.request_data.internship_company }}</b> 
                    during the period <b>{{ request.request_data.internship_duration }}</b>.
                </p>
            """,
            "required_fields": {**default_fields, "internship_company": True, "internship_duration": True}
        },
        {
            "name": "Fee Structure Certificate",
            "description": "Details the fee structure for a student for a specific academic year.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Fee Structure Certificate</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that the fee structure for <b>{{ student.full_name }}</b> (Roll No.: <b>{{ student.enrollment_no }}</b>), 
                    a student of <b>{{ student.degree }}</b> in <b>{{ student.branch }}</b> for the academic session <b>{{ student.academic_session }}</b> is as follows:
                </p>
                <p style="text-align: justify; font-size: 16px; line-height: 1.6; margin-top: 15px; padding-left: 20px;">
                    Tuition Fee: Rs. 100,000/- <br>
                    Examination Fee: Rs. 4,000/- <br>
                    Degree Fee: Rs. 1,000/- <br>
                    Sports Fee: Rs. 300/- <br>
                    Innovation Fee: Rs. 300/- <br>
                    Library Fee: Rs. 200/- <br>
                    <b>TOTAL: Rs. 105,800/-</b>
                </p>
            """,
            "required_fields": default_fields
        },
        {
            "name": "Scholarship Certificate (Pragati/Saksham/Swanath)",
            "description": "A bonafide certificate specifically for AICTE scholarships on the National Scholarship Portal (NSP).",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Bonafide Certificate for Scholarship</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that <b>{{ student.full_name }}</b> (Roll No. <b>{{ student.enrollment_no }}</b>) is a bonafide student of <b>{{ student.degree }} ({{ student.branch }})</b> 
                    in the current Academic year {{ student.academic_session }}.
                    <br><br>
                    {{ student.pronoun_he_she|capfirst }} has applied for AICTE Pragati/Saksham/Swanath Scholarship on NSP and {{ student.pronoun_his_her }} Application ID is 
                    <b>{{ request.request_data.application_id }}</b>. As per our records, {{ student.pronoun_his_her }} domicile state is UTTAR PRADESH.
                </p>
            """,
            "required_fields": {**default_fields, "application_id": True}
        },
        {
            "name": "Caste Certificate Forwarding Letter",
            "description": "A forwarding letter for the verification of a student's caste certificate.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Forwarding Letter</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This letter is to forward the caste certificate of <b>{{ student.full_name }}</b> (Roll No.: <b>{{ student.enrollment_no }}</b>), 
                    a student of <b>{{ student.degree }}</b>. The student belongs to the <b>{{ request.request_data.caste_category }}</b> category. 
                    This is for the purpose of official verification.
                </p>
            """,
            "required_fields": {**default_fields, "caste_category": True}
        },
        {
            "name": "Gap Certificate",
            "description": "An affidavit-style certificate where a student declares the reason for an academic gap.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Gap Certificate</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    I, <b>{{ student.full_name }}</b> {{ student.parent_relation }} <b>{{ student.father_name }}</b>, hereby declare that there was a gap in my studies for the duration of 
                    <b>{{ request.request_data.gap_duration }}</b>. The reason for this gap was <b>{{ request.request_data.gap_reason }}</b>. 
                    I assure you that during this period, I was not involved in any unlawful activities.
                </p>
            """,
            "required_fields": {**default_fields, "gap_duration": True, "gap_reason": True}
        },
        {
            "name": "Transfer Certificate",
            "description": "Official document issued when a student is transferring to another institution.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Transfer Certificate</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that <b>{{ student.full_name }}</b> (Roll No.: <b>{{ student.enrollment_no }}</b>) was a student of this institute. 
                    {{ student.pronoun_he_she|capfirst }} is being transferred for the following reason: <b>{{ request.request_data.transfer_reason }}</b>. 
                    We have no objection to {{ student.pronoun_his_her }} admission into any other institution.
                </p>
            """,
            "required_fields": {**default_fields, "transfer_reason": True}
        },
        {
            "name": "Provisional Degree Certificate",
            "description": "A provisional certificate issued after course completion, pending the official degree.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Provisional Degree Certificate</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that <b>{{ student.full_name }}</b> (Roll No.: <b>{{ student.enrollment_no }}</b>) 
                    has successfully completed the <b>{{ student.degree }}</b> in <b>{{ student.branch }}</b> 
                    in the academic session {{ student.academic_session }}. The final degree will be awarded at the next convocation.
                </p>
            """,
            "required_fields": default_fields
        },
        {
            "name": "Medium of Instruction Certificate",
            "description": "Certifies that the medium of instruction for the student's course was English.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Medium of Instruction</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that <b>{{ student.full_name }}</b> (Roll No.: <b>{{ student.enrollment_no }}</b>) 
                    completed the <b>{{ student.degree }}</b> in <b>{{ student.branch }}</b> from this university. 
                    The medium of instruction throughout the course of study was <b>{{ request.request_data.medium_of_instruction }}</b>.
                </p>
            """,
            "required_fields": {**default_fields, "medium_of_instruction": True}
        },
        {
            "name": "Fee Structure Certificate",
            "description": "Details the fee structure for a student for a specific academic year.",
            "body_template": """
                <p style="text-align: justify; font-size: 15px; line-height: 1.6;">
                    It is to certify that <strong>{{ student.full_name }}</strong> S/o / D/o <strong>{{ student.father_name }}</strong> (Roll No.: <strong>{{ student.enrollment_no }}</strong>) is a <strong>{{ year_in_words }} year</strong> bonafide student of Four Year B.Tech. <strong>{{ student.branch }}</strong> at the University Institute of Engineering & Technology, Chhatrapati Shahu Ji Maharaj University, Kanpur.
                </p>

                <p style="text-align: justify; font-size: 15px; margin-bottom: 20px;">
                    The fee structure for the remaining academic duration starting from <strong>Year {{ requested_year }}</strong> is as follows:
                </p>

                <table border="1" style="width: 50%; border-collapse: collapse; text-align: center; font-size: 14px; margin-top: 15px; margin-bottom: 25px;">
                    <thead>
                        <tr style="background-color: #f0f0f0;">
                            <th style="padding: 8px;">Academic Year</th>
                            <th style="padding: 8px;">Total Fee Amount (Rs)</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for fee in fee_data %}
                        <tr>
                            <td style="padding: 8px;"><strong>{{ fee.year_label }}</strong></td>
                            <td style="padding: 8px;">{{ fee.amount }}</td>
                        </tr>
                        {% endfor %}
                        
                        <tr style="background-color: #e8e8e8;">
                            <td style="padding: 8px ;"><strong>Grand Total:</strong></td>
                            <td style="padding: 8px; font-size: 14px;"><strong>Rs {{ grand_total }}</strong></td>
                        </tr>
                    </tbody>
                </table>

<div style="margin-top: 15px; padding-top: 10px; font-size: 13px; line-height: 1.5;">
    <p style="margin: 0; padding: 0;"><strong>Bank Account Details for RTGS / NEFT / Remittance:</strong></p>
    
    <p style="margin: 2px 0 0 0; padding: 0;">
        &nbsp;&nbsp<strong>Account Name:</strong> Finance Officer of CSJM University in Kanpur
    </p>
    <p style="margin: 2px 0 0 0; padding: 0;">
        &nbsp;&nbsp<strong>Bank Name:</strong> State Bank of India
    </p>
    <p style="margin: 2px 0 0 0; padding: 0;">
        &nbsp;&nbsp<strong>Account Number:</strong> 00000040465185585
    </p>
    <p style="margin: 2px 0 0 0; padding: 0;">
        &nbsp;&nbsp<strong>IFSC Code:</strong> SBIN0064085
    </p>
</div>

                <p style="font-size: 12px; margin-top: 20px; color: #555; font-style: italic;">
                    * Note: This is an estimated fee structure for bank loan purposes only.
                </p>
            """,
            "required_fields": {**default_fields, "fee_year": True}
        },
        {
            "name": "Rank Certificate",
            "description": "Certifies the rank obtained by a student in their program among their batchmates.",
            "body_template": """
                <h2 style="text-decoration: underline; font-weight: bold; margin-top: 60px; margin-bottom: 40px;">Rank Certificate</h2>
                <p style="text-align: justify; font-size: 18px; line-height: 1.8;">
                    This is to certify that <b>{{ student.full_name }}</b> (Roll No.: <b>{{ student.enrollment_no }}</b>) 
                    has secured the <b>{{ request.request_data.rank_achieved }}</b> in the <b>{{ student.degree }}</b> 
                    in <b>{{ student.branch }}</b> for the academic session {{ student.academic_session }} 
                    out of a total of <b>{{ request.request_data.total_students }}</b> students.
                </p>
            """,
            "required_fields": {**default_fields, "rank_achieved": True, "total_students": True}
        }
        
    ]
    
    for template in templates_data:
        CertificateTemplate.objects.update_or_create(
            name=template["name"],
            defaults={
                'description': template.get("description", ""),
                'body_template': template.get("body_template", ""),
                'required_fields': template.get("required_fields", {})
            }
        )

def delete_templates(apps, schema_editor):
    """
    Deletes the predefined templates if the migration is reversed.
    """
    CertificateTemplate = apps.get_model('certificates', 'CertificateTemplate')
    template_names = [t["name"] for t in templates_data]
    CertificateTemplate.objects.filter(name__in=template_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_templates, reverse_code=delete_templates),
    ]

