# Generated by Django 4.2.3 on 2025-12-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "certificates",
            "0006_student_blood_group_student_category_student_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["enrollment_no"], "verbose_name_plural": "Students"},
        ),
    ]
