# Generated by Django 4.2.3 on 2025-12-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0007_alter_student_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="correction_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason provided by student for correction",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="certificaterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CORRECTION", "Correction Requested"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="certificaterequest",
            name="verification_document",
            field=models.FileField(
                blank=True,
                help_text="Marksheet for verification",
                null=True,
                upload_to="verification_docs/",
            ),
        ),
        migrations.AlterField(
            model_name="generatedcertificate",
            name="generated_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="generated_certificates/"
            ),
        ),
        migrations.AlterField(
            model_name="generatedcertificate",
            name="reference_no",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
