# Generated by Django 4.2.3 on 2026-01-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0013_certificaterequest_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Course Code"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Subject Name")),
                ("credits", models.IntegerField(default=0, verbose_name="Credits")),
                (
                    "is_practical",
                    models.BooleanField(default=False, verbose_name="Is Practical?"),
                ),
            ],
            options={
                "ordering": ["course_code"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Faculty Name"),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Employee ID"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Faculty Member",
                "verbose_name_plural": "Faculty Members",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="CourseAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        default="2025-26(1)",
                        help_text="e.g. 2025-26(1) or 2024-25(2)",
                        max_length=50,
                    ),
                ),
                ("branch", models.CharField(max_length=100, verbose_name="Branch")),
                ("semester", models.IntegerField(verbose_name="Semester")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="certificates.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="certificates.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Allocation",
                "verbose_name_plural": "Course Allocations",
                "unique_together": {("session", "branch", "semester", "subject")},
            },
        ),
        migrations.CreateModel(
            name="AcademicRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField(verbose_name="Semester")),
                ("sgpa", models.FloatField(default=0.0, verbose_name="SGPA")),
                ("cpi", models.FloatField(default=0.0, verbose_name="CPI")),
                ("total_backlogs", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_records",
                        to="certificates.student",
                    ),
                ),
            ],
            options={
                "ordering": ["semester"],
                "unique_together": {("student", "semester")},
            },
        ),
    ]
