# Generated by Django 4.2.3 on 2026-05-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0014_subject_teacher_courseallocation_academicrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="signed_application",
            field=models.FileField(
                blank=True,
                help_text="Application signed by the external authority where the document is to be submitted.",
                null=True,
                upload_to="external_signed_applications/",
            ),
        ),
    ]
