# Generated by Django 4.2.3 on 2026-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campus_media",
            "0002_comment_mutelist_publicpost_remove_message_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="publicpost",
            name="is_announcement",
            field=models.BooleanField(
                default=False, help_text="Pinned announcement with comments disabled."
            ),
        ),
    ]
