# Generated by Django 4.2.3 on 2025-08-14 21:44

import certificates.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Certificate Name"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "body_template",
                    models.TextField(
                        help_text="The main text of the certificate with placeholders like {{ student.full_name }}."
                    ),
                ),
                (
                    "required_fields",
                    models.JSONField(
                        blank=True,
                        default=certificates.models.get_default_required_fields,
                        help_text="Defines extra fields needed for this certificate type.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Certificate Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Signatory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Full Name or Stamp Name"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Designation (if applicable)",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=certificates.models.get_signature_path,
                        verbose_name="Digital Signature/Stamp Image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Signatories & Stamps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                (
                    "father_name",
                    models.CharField(max_length=255, verbose_name="Father's Name"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "enrollment_no",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Enrollment Number"
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        max_length=100, verbose_name="Degree (e.g., B.Tech)"
                    ),
                ),
                ("branch", models.CharField(max_length=100, verbose_name="Branch")),
                (
                    "academic_session",
                    models.CharField(
                        max_length=20, verbose_name="Academic Session (e.g., 2021-2025)"
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Students",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="CertificateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True,
                        help_text="Stores dynamic data like CPI, company name etc.",
                        null=True,
                    ),
                ),
                (
                    "verification_document",
                    models.FileField(
                        blank=True,
                        help_text="Marksheet for CPI/CGPA verification",
                        null=True,
                        upload_to=certificates.models.get_verification_document_path,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="certificates.student",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="certificates.certificatetemplate",
                        verbose_name="Certificate Type",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Certificate Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedCertificate",
            fields=[
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="certificates.certificaterequest",
                    ),
                ),
                (
                    "certificate_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Publicly verifiable unique ID",
                        unique=True,
                    ),
                ),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True,
                        default=certificates.models.generate_reference_no,
                        max_length=100,
                    ),
                ),
                (
                    "generated_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=certificates.models.get_generated_certificate_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signatories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="signed_certificates",
                        to="certificates.signatory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Generated Certificates",
                "ordering": ["-created_at"],
            },
        ),
    ]
