# Generated by Django 4.2.3 on 2025-12-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_populate_certificate_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedcertificate",
            name="certificate_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 Hash for Blockchain Verification",
                max_length=64,
                null=True,
            ),
        ),
    ]
