# Generated by Django 4.2.3 on 2025-12-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0004_alter_certificaterequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificaterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
