# Generated by Django 4.2.3 on 2025-12-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0005_alter_certificaterequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="blood_group",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Permanent District"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="local_address",
            field=models.TextField(blank=True, null=True, verbose_name="Local Address"),
        ),
        migrations.AddField(
            model_name="student",
            name="local_district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Local District"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="local_pincode",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Local Pincode"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mother Name"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_contact",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Parent Contact No"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="permanent_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Permanent Address"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Student Contact No"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pincode",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Permanent Pincode"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="State"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="sub_category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="academic_session",
            field=models.CharField(
                default="2022-2026", max_length=20, verbose_name="Academic Session"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="degree",
            field=models.CharField(
                default="B.Tech", max_length=100, verbose_name="Degree"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_name",
            field=models.CharField(max_length=255, verbose_name="Father Name"),
        ),
    ]
