# Generated by Django 4.2.3 on 2025-12-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0009_helpquery"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="is_self_declared",
            field=models.BooleanField(
                default=False, help_text="Student accepted profile correctness"
            ),
        ),
        migrations.AddField(
            model_name="certificaterequest",
            name="purpose",
            field=models.TextField(
                default="General Application",
                help_text="Reason for applying (e.g. Visa, Higher Studies)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certificaterequest",
            name="submitting_to",
            field=models.CharField(
                default="Not Specified",
                help_text="Organization Name (e.g. TCS, Passport Office)",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
