# Generated by Django 4.2.3 on 2025-12-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0011_paymenttransaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentTransaction",
        ),
    ]
