# Generated by Django 4.2.3 on 2025-12-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0012_delete_paymenttransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="priority",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("High", "High")],
                default="Normal",
                max_length=20,
            ),
        ),
    ]
